### ISSUE TITLE
Landing Page UI Design and Implementation

### ISSUE THREAD

**Issue by matthewviegas** [ECE444-2020Fall/project1-webapp-group18-jimwaukees#10]
Create a landing page for the web-app. The page must include the following elements:

- [x] Search bar for meal-based queries
- [x] Element to add ingredients for recipe searches, either by textual input or user selection (to be decided)
- [x] Name of web-app and brief description of how to use the app or what it is
- [x] Link to a help page or help pop-up

**Comment by honeyjoo** [comment]
tab at the top and a search bar in JS
React: component (like a fx) returns an HTML
